/**
 * Catálogo central de textos visibles de la consola (español).
 *
 * Regla del proyecto: cero texto hardcodeado en componentes nuevos. Todo texto
 * visible de las features administrativas sale de aquí, tipado: una errata en la
 * clave no compila. No es un framework de i18n — es el formato simple aprobado
 * hasta que exista una segunda lengua.
 */
const VERTICAL_LABELS = {
  RESTAURANT: 'Restaurante',
  NIGHTCLUB: 'Discoteca',
  EVENT_HALL: 'Salón de eventos',
  HOTEL: 'Hotel',
} as const;

export const STRINGS = {
  brand: {
    name: 'MapIt',
  },
  shell: {
    brandArea: 'Plataforma',
    nav: {
      dashboard: 'Dashboard',
      tenants: 'Tenants',
      settings: 'Configuración',
      profile: 'Perfil',
    },
    logout: 'Cerrar sesión',
    openMenu: 'Abrir navegación',
    closeMenu: 'Cerrar navegación',
    roleLabels: {
      SUPER_ADMIN: 'Super Admin',
      ADMIN: 'Administrador',
      MANAGER: 'Gerente',
      STAFF: 'Staff',
    },
    sectionPending: 'Esta sección estará disponible en una próxima iteración.',
  },
  /** Shell de la consola operativa de staff (por tenant). */
  staffShell: {
    brandArea: 'Consola',
    nav: {
      home: 'Inicio',
      business: 'Mi negocio',
    },
  },
  adminDashboard: {
    title: 'Dashboard',
    eyebrow: 'MapIt · Plataforma',
    greeting: 'Panel de administración de la plataforma',
    intro: 'Gestiona las empresas registradas y su ciclo de vida desde un solo lugar.',
    quickActionsTitle: 'Accesos rápidos',
    goToTenants: 'Ir a Tenants',
    tenantsWithData: 'tenants registrados',
    tenantsActive: 'activos',
    tenantsSuspended: 'suspendidos',
    loading: 'Cargando resumen…',
    loadError: 'No se pudo cargar el resumen. Inténtalo de nuevo.',
    retry: 'Reintentar',
  },
  /** Traducciones de las verticales de negocio: una sola fuente para toda la app. */
  verticals: VERTICAL_LABELS,
  tenants: {
    title: 'Tenants',
    intro: 'Empresas registradas en la plataforma. El negocio suspende; no hay borrado físico.',
    newTenant: 'Nuevo tenant',
    searchPlaceholder: 'Buscar por nombre o slug…',
    searchLabel: 'Buscar tenants',
    filterStatus: 'Filtrar por estado',
    allStatuses: 'Todos',
    paginationLabel: 'Paginación',
    statusLabels: {
      ACTIVE: 'Activo',
      SUSPENDED: 'Suspendido',
    },
    verticalLabels: VERTICAL_LABELS,
    columns: {
      name: 'Nombre',
      slug: 'Slug',
      vertical: 'Vertical',
      status: 'Estado',
      createdAt: 'Creado',
      actions: 'Acciones',
    },
    loading: 'Cargando tenants…',
    empty: 'No hay tenants que coincidan con los filtros.',
    emptyTitle: 'Sin resultados',
    error: 'No se pudo cargar el listado. Inténtalo de nuevo.',
    retry: 'Reintentar',
    viewDetail: 'Ver detalle',
    previous: 'Anterior',
    next: 'Siguiente',
    pageOf: 'de',
    ofTotal: 'de',
  },
  tenantForm: {
    createEyebrow: 'MapIt · Administración de plataforma',
    createTitle: 'Nuevo tenant',
    createIntro: 'Registra una empresa en la plataforma y define su vertical inicial.',
    editTitle: 'Editar tenant',
    nameLabel: 'Nombre de la organización',
    namePlaceholder: 'Ej. Restaurante Central',
    nameError: 'Ingresa un nombre de hasta 120 caracteres.',
    slugLabel: 'Slug',
    slugPlaceholder: 'restaurante-central',
    slugHint: 'Minúsculas, números y guiones. Identifica la empresa en las URLs.',
    slugError: 'El slug debe tener entre 2 y 63 caracteres válidos.',
    slugImmutable: 'El slug no se puede modificar después del alta.',
    verticalLabel: 'Vertical de negocio',
    verticalImmutable: 'La vertical se asigna al crear el tenant y no se puede modificar.',
    adminEmailLabel: 'Correo del administrador',
    adminEmailPlaceholder: 'admin@empresa.com',
    adminEmailError: 'Ingresa un correo válido.',
    adminEmailHint: 'Recibirá la confirmación del alta. Se usará para la invitación (CU-25).',
    submitCreate: 'Registrar tenant',
    submitSaving: 'Registrando…',
    submitEdit: 'Guardar cambios',
    submitEditing: 'Guardando…',
    registerAnother: 'Registrar otro',
    cancel: 'Cancelar',
    backToList: 'Volver al listado',
    successCreate: 'Tenant registrado correctamente.',
    successUpdate: 'Cambios guardados.',
    successIdPrefix: 'ID:',
    errors: {
      badRequest: 'Revisa los datos ingresados.',
      unauthorized: 'Tu sesión expiró. Vuelve a iniciar sesión.',
      forbidden: 'No tienes permisos para esta operación.',
      slugConflict: 'El slug ya está registrado por otra empresa.',
      emailUnavailable: 'No se pudo enviar el correo de confirmación. Inténtalo de nuevo.',
      generic: 'No se pudo completar la operación. Inténtalo de nuevo.',
    },
  },
  tenantDetail: {
    title: 'Detalle del tenant',
    notFound: 'El tenant no existe o fue dado de baja.',
    loading: 'Cargando detalle…',
    loadError: 'No se pudo cargar el detalle. Inténtalo de nuevo.',
    retry: 'Reintentar',
    fieldName: 'Nombre',
    fieldSlug: 'Slug',
    fieldVertical: 'Vertical',
    fieldStatus: 'Estado',
    fieldCreatedAt: 'Alta',
    fieldUpdatedAt: 'Última modificación',
    editAction: 'Editar',
    suspendAction: 'Suspender',
    reactivateAction: 'Reactivar',
    confirmSuspendTitle: 'Suspender tenant',
    confirmSuspendMessage:
      'Los usuarios de esta empresa no podrán iniciar sesión mientras esté suspendida. ¿Continuar?',
    confirmReactivateTitle: 'Reactivar tenant',
    confirmReactivateMessage: 'La empresa recuperará el acceso de inmediato. ¿Continuar?',
    confirm: 'Confirmar',
    cancel: 'Cancelar',
    statusUpdated: 'Estado actualizado.',
  },
  login: {
    title: 'Iniciar sesión',
    subtitle: 'Ingresa tus credenciales para acceder a la plataforma.',
    emailLabel: 'Correo electrónico',
    emailPlaceholder: 'tu.correo@ejemplo.com',
    passwordLabel: 'Contraseña',
    passwordToggleShow: 'Mostrar contraseña',
    passwordToggleHide: 'Ocultar contraseña',
    rememberMe: 'Recordarme',
    forgotPassword: '¿Olvidaste tu contraseña?',
    submit: 'Iniciar sesión',
    submitting: 'Iniciando sesión…',
    newBusiness: '¿Nuevo negocio?',
    requestAccess: 'Solicita acceso',
    termsPrefix: 'Al continuar, aceptas nuestros',
    termsLink: 'Términos de Servicio',
    privacyLink: 'Política de Privacidad',
    showcaseAriaLabel: 'Plataforma MapIt',
    showcaseHeadlineA: 'Mapea tu negocio, opéralo en',
    showcaseHighlight: 'Tiempo Real',
    showcaseIntro:
      'La plataforma inteligente para gestionar mesas, barras y zonas con máxima agilidad y control operativo.',
    showcaseQuote:
      '“Esta plataforma nos ha permitido coordinar los espacios y atender a los clientes con una velocidad y precisión nunca antes vista.”',
    decorativePaths: 'Curvas dinámicas decorativas',
    logoAlt: 'MapIt',
    errors: {
      emailRequired: 'Ingresa tu correo electrónico.',
      emailInvalid: 'Ingresa un correo electrónico válido.',
      passwordRequired: 'Ingresa tu contraseña.',
      missingTenantLink: 'Abre el enlace de acceso de tu empresa para continuar.',
      startFailed: 'No se pudo iniciar la sesión. Inténtalo de nuevo.',
      invalidCredentials: 'Credenciales inválidas.',
      connection: 'No pudimos conectar con el servicio. Inténtalo de nuevo.',
    },
    help: {
      password:
        'La recuperación de contraseña aún no está disponible. Contacta al administrador de tu empresa.',
      access: 'Las solicitudes de acceso aún no están disponibles desde esta pantalla.',
    },
    passwordStrength: {
      length: '8 caracteres o más',
      casing: 'Mayúsculas y minúsculas',
      digit: 'Un número',
      symbol: 'Un símbolo',
      labels: ['Vacía', 'Débil', 'Aceptable', 'Buena', 'Fuerte'],
      announcePrefix: 'Fortaleza de la contraseña:',
      commonPattern: 'Es un patrón muy común.',
      warningLabel: 'Patrón muy común',
      allRulesMet: 'Cumples todos los requisitos.',
      missingPrefix: 'Falta:',
      ruleMetSr: '(cumplido)',
      rulePendingSr: '(pendiente)',
    },
  },
  home: {
    title: 'MapIt · Consola',
    sub: 'Mapea tu negocio, opéralo en tiempo real.',
    welcome: 'Bienvenido,',
    tenantLabel: 'Empresa:',
    roleLabel: 'Rol:',
    logout: 'Cerrar sesión',
    flagBannerTitle: 'El feature toggle está activo.',
    flagBannerBody: 'Apaga demo.hello en Unleash (:4242) y este banner desaparece sin recompilar.',
    paymentsQrEnabled: 'El pago con QR está habilitado (CU-17).',
  },
  notFound: {
    code: '404',
    title: 'Esta página no existe.',
    backHome: 'Volver al inicio',
  },
  demoItems: {
    eyebrow: 'MapIt · prueba de integración',
    title: 'Elementos de demostración',
    intro: 'CRUD completo conectado a Angular, Spring Boot y PostgreSQL.',
    newItem: 'Nuevo elemento',
    form: {
      eyebrowEdit: 'Edición',
      eyebrowNew: 'Alta',
      titleEdit: 'Editar elemento',
      titleNew: 'Crear elemento',
      nameLabel: 'Nombre',
      namePlaceholder: 'Ej. Mesa terraza',
      descriptionLabel: 'Descripción',
      descriptionPlaceholder: 'Describe el elemento',
      activeLabel: 'Elemento activo',
      submit: 'Crear elemento',
      submitEdit: 'Guardar cambios',
      submitting: 'Guardando…',
      cancel: 'Cancelar',
    },
    list: {
      eyebrow: 'Consulta',
      title: 'Elementos guardados',
      loading: 'Cargando elementos…',
      empty: 'Todavía no hay elementos. Crea el primero.',
      activeBadge: 'Activo',
      inactiveBadge: 'Inactivo',
      noDescription: 'Sin descripción',
      updatedPrefix: 'Actualizado',
      edit: 'Editar',
      remove: 'Eliminar',
    },
    errors: {
      load: 'No se pudieron cargar los elementos.',
      nameRequired: 'El nombre es obligatorio.',
      save: 'No se pudo guardar el elemento.',
      remove: 'No se pudo eliminar el elemento.',
    },
  },
  establishments: {
    eyebrow: 'MapIt · administración',
    title: 'Establecimientos',
    intro: 'Los lugares físicos que tu empresa opera en MapIt.',
    new: 'Nuevo establecimiento',
    form: {
      eyebrowEdit: 'Edición',
      eyebrowNew: 'Alta',
      titleEdit: 'Editar establecimiento',
      titleNew: 'Crear establecimiento',
      nameLabel: 'Nombre',
      namePlaceholder: 'Ej. Bar Central',
      typeLabel: 'Tipo',
      typeImmutable:
        'El tipo no se puede cambiar: define qué plantillas de elemento aplican al mapa.',
      slugLabel: 'Slug',
      slugPlaceholder: 'bar-central',
      slugHint: 'Se usa en la URL pública de reserva. Minúsculas, dígitos y guiones.',
      timezoneLabel: 'Zona horaria',
      timezonePlaceholder: 'America/La_Paz',
      submit: 'Crear establecimiento',
      submitEdit: 'Guardar cambios',
      submitting: 'Guardando…',
      cancel: 'Cancelar',
    },
    list: {
      eyebrow: 'Consulta',
      title: 'Establecimientos registrados',
      loading: 'Cargando establecimientos…',
      empty: 'Todavía no hay establecimientos. Crea el primero.',
      updatedPrefix: 'Actualizado',
      edit: 'Editar',
      remove: 'Dar de baja',
    },
    removeConfirm: '¿Dar de baja "{name}"? Dejará de aparecer, pero no se borra el histórico.',
    errors: {
      load: 'No se pudieron cargar los establecimientos.',
      nameRequired: 'El nombre es obligatorio.',
      slugInvalid: 'El slug debe tener entre 2 y 63 caracteres: minúsculas, dígitos y guiones.',
      slugConflict: 'Ya existe un establecimiento con ese slug.',
      save: 'No se pudo guardar el establecimiento.',
      remove: 'No se pudo dar de baja el establecimiento.',
    },
  },
  /**
   * Textos de la gestión de Pisos, Sectores y Elementos espaciales (CU-05 / HU-2.03).
   * Antes vivían en `features/spaces/model/spaces.strings.ts`; ahora salen de aquí,
   * la fuente única de strings de la consola.
   */
  spaces: {
    wizard: {
      stepperAriaLabel: 'Progreso del asistente',
      stepBusiness: 'Datos del negocio',
      stepBusinessAriaLabel: 'Paso 1: Datos del negocio, completado',
      stepBusinessCurrentAriaLabel: 'Paso 1: Datos del negocio, actual',
      stepStructure: 'Estructura del espacio',
      stepStructureAriaLabel: 'Paso 2: Estructura del espacio, actual',
      stepStructurePendingAriaLabel: 'Paso 2: Estructura del espacio, pendiente',
      pageTitle: 'Estructura del espacio',
      pageDescription:
        'Define la jerarquía física de tu ubicación. Empieza creando plantas y luego añade sectores o zonas a cada una.',
      dragReorder: 'Arrastra para reordenar',
      addFloor: 'Agregar piso',
      previous: 'Anterior',
      next: 'Siguiente',
      finish: 'Finalizar',
      step1Title: 'Configuración del establecimiento',
      nameLabel: 'Nombre del establecimiento',
      namePlaceholder: 'Ej. Gran Hotel Plaza',
      typeLabel: 'Tipo de establecimiento',
      addressLabel: 'Dirección',
      addressPlaceholder: 'Calle principal 123',
      timezoneLabel: 'Zona horaria',
      timezonePlaceholder: 'Selecciona una zona',
      creating: 'Creando…',
      createFailed: 'No se pudo crear el establecimiento. Inténtalo de nuevo.',
      nameRequired: 'Ingresa el nombre del establecimiento.',
      typeRequired: 'Selecciona el tipo de establecimiento.',
    },
    floors: {
      title: 'Plantas',
      subtitle: 'Gestión de pisos del establecimiento',
      empty: 'No hay plantas registradas. Crea la primera.',
      loading: 'Cargando plantas…',
      createButton: 'Nueva planta',
      form: {
        createTitle: 'Crear planta',
        editTitle: 'Editar planta',
        eyebrowNew: 'Alta',
        eyebrowEdit: 'Edición',
        nameLabel: 'Nombre',
        namePlaceholder: 'Ej. Planta baja',
        nameMaxLength: 100,
        nameRequired: 'El nombre es obligatorio.',
        nameTooLong: 'El nombre no puede exceder los 100 caracteres.',
        levelLabel: 'Nivel',
        slugHint: 'El slug se genera automáticamente a partir del nombre y no se puede editar.',
        cancelButton: 'Cancelar',
        saveButton: 'Crear planta',
        updateButton: 'Guardar cambios',
        saving: 'Guardando…',
      },
      list: {
        sectionAriaLabel: 'Pisos y sectores',
        reorderAriaLabel: 'Arrastrar para reordenar piso',
        nameHeader: 'Nombre',
        slugHeader: 'Slug',
        levelHeader: 'Nivel',
        actionsHeader: 'Acciones',
        editButton: 'Editar',
        deleteButton: 'Eliminar',
        deleteConfirm: '¿Eliminar la planta "{name}"? Esta acción no se puede deshacer.',
      },
      errors: {
        loadFailed: 'No se pudieron cargar las plantas.',
        saveFailed: 'No se pudo guardar la planta.',
        deleteFailed: 'No se pudo eliminar la planta.',
        slugConflict: 'Ya existe una planta con ese slug.',
        notFound: 'Planta no encontrada.',
      },
    },
    sectors: {
      title: 'Sectores',
      subtitle: 'Gestión de sectores por planta',
      empty: 'No hay sectores en esta planta. Crea el primero.',
      loading: 'Cargando sectores…',
      createButton: 'Nuevo sector',
      addButton: 'Agregar Sector',
      form: {
        createTitle: 'Crear sector',
        editTitle: 'Editar sector',
        eyebrowNew: 'Nuevo sector',
        nameLabel: 'Nombre',
        namePlaceholder: 'Ej. Terraza norte',
        nameMaxLength: 100,
        nameRequired: 'El nombre es obligatorio.',
        nameTooLong: 'El nombre no puede exceder los 100 caracteres.',
        slugHint: 'El slug se genera automáticamente a partir del nombre.',
        cancelButton: 'Cancelar',
        saveButton: 'Crear sector',
        updateButton: 'Guardar cambios',
        saving: 'Guardando…',
      },
      list: {
        reorderAriaLabel: 'Arrastrar para reordenar sector',
        nameHeader: 'Nombre',
        slugHeader: 'Slug',
        capacityHeader: 'Capacidad máx.',
        actionsHeader: 'Acciones',
        editButton: 'Editar',
        deleteButton: 'Eliminar',
        deleteConfirm: '¿Eliminar el sector "{name}"? Esta acción no se puede deshacer.',
      },
      errors: {
        loadFailed: 'No se pudieron cargar los sectores.',
        saveFailed: 'No se pudo guardar el sector.',
        deleteFailed: 'No se pudo eliminar el sector.',
        slugConflict: 'Ya existe un sector con ese slug en esta planta.',
        floorNotFound: 'La planta seleccionada no existe.',
        notFound: 'Sector no encontrado.',
      },
    },
    elements: {
      title: 'Elementos espaciales',
      subtitle: 'Mesas, barras, butacas y zonas dentro de un sector',
      empty: 'Aún no hay elementos en este sector. Registra el primero.',
      loading: 'Cargando elementos…',
      createButton: 'Nuevo elemento',
      form: {
        createTitle: 'Registrar elemento',
        editTitle: 'Editar elemento',
        typeLabel: 'Tipo',
        xLabel: 'X',
        yLabel: 'Y',
        initialStateLabel: 'Estado inicial',
        stateLockedHint: 'El estado se transiciona en la operación (HU-3.01), no en la edición',
        coordsHint: 'Coordenadas relativas al sector, desde la esquina superior izquierda.',
        coordsInvalid: 'X e Y deben ser números no negativos (relativos al sector).',
        cancelButton: 'Cancelar',
        saveButton: 'Registrar',
        updateButton: 'Guardar cambios',
        saving: 'Guardando…',
      },
      types: {
        TABLE: 'Mesa',
        BAR: 'Barra',
        SECTOR_ZONE: 'Zona',
        STAGE: 'Escenario',
        SEAT: 'Butaca numerada',
        ROOM: 'Habitación',
        DECOR: 'Decoración',
      },
      states: {
        AVAILABLE: 'Disponible',
        OCCUPIED: 'Ocupado',
        RESERVED: 'Reservado',
        CLEANING: 'Limpieza',
        OUT_OF_SERVICE: 'Fuera de servicio',
      },
      list: {
        typeHeader: 'Tipo',
        coordHeader: 'Ubicación (X, Y)',
        stateHeader: 'Estado',
        actionsHeader: 'Acciones',
        editButton: 'Editar',
      },
      stateAction: {
        groupAriaLabel: 'Seleccionar nuevo estado operativo',
        changeButton: 'Cambiar estado',
        changeAriaLabel: 'Cambiar estado operativo del elemento',
        label: 'Nuevo estado',
        selectAriaLabel: 'Nuevo estado operativo',
        confirmButton: 'Aplicar',
        cancelButton: 'Cancelar',
      },
      errors: {
        loadFailed: 'No se pudieron cargar los elementos.',
        saveFailed: 'No se pudo guardar el elemento.',
        saveInvalid:
          'Tipo o coordenadas rechazados por el servidor. Revisa el tipo permitido para tu vertical.',
        notFound: 'Elemento no encontrado.',
      },
    },
  },
} as const;

export type AppStrings = typeof STRINGS;
