import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import type {
  Establishment,
  EstablishmentCreateRequest,
  Floor,
  Sector,
  FloorCreateRequest,
  SectorCreateRequest,
  SpaceElement,
  SpaceElementCreateRequest,
  SpaceElementUpdateRequest,
} from '@mapit/api-client';
import { EstablishmentsService, SpacesService } from '@mapit/api-client';
import type { Observable } from 'rxjs';

import { RuntimeConfigStore } from '../../../core/runtime-config';

export interface FloorDraft {
  name: string;
  level: number;
}

export interface SectorDraft {
  name: string;
}

export interface EstablishmentDraft {
  name: string;
  type: string;
  address: string;
  timezone: string;
}

@Injectable({ providedIn: 'root' })
export class SpacesApiService {
  private readonly api = inject(SpacesService);
  private readonly establishmentsApi = inject(EstablishmentsService);
  private readonly http = inject(HttpClient);
  private readonly runtime = inject(RuntimeConfigStore);

  /** GET /api/v1/establishments/{establishmentId}/floors */
  listFloors(establishmentId: string): Observable<Floor[]> {
    return this.api.listFloorsByEstablishment({ establishmentId });
  }

  /** POST /api/v1/establishments — paso 1 del asistente de configuración. */
  createEstablishment(request: EstablishmentCreateRequest): Observable<Establishment> {
    return this.establishmentsApi.createEstablishment({ establishmentCreateRequest: request });
  }

  /** GET /api/v1/establishments/{id} — paso 3 del asistente (resumen). */
  getEstablishment(id: string): Observable<Establishment> {
    return this.establishmentsApi.getEstablishment({ id });
  }

  /** GET /api/v1/floors/{id} */
  getFloor(id: string): Observable<Floor> {
    return this.api.getFloor({ id });
  }

  /** POST /api/v1/establishments/{establishmentId}/floors */
  createFloor(request: FloorCreateRequest, establishmentId: string): Observable<Floor> {
    return this.api.createFloor({ establishmentId, floorCreateRequest: request });
  }

  /** PUT /api/v1/floors/{id} */
  updateFloor(id: string, request: FloorCreateRequest): Observable<Floor> {
    return this.api.updateFloor({ id, floorCreateRequest: request });
  }

  /** DELETE /api/v1/floors/{id} */
  deleteFloor(id: string): Observable<unknown> {
    return this.api.deleteFloor({ id });
  }

  // ===== SECTORS =====

  /** GET /api/v1/floors/{floorId}/sectors */
  listSectorsByFloor(floorId: string): Observable<Sector[]> {
    return this.api.listSectorsByFloor({ floorId });
  }

  /** POST /api/v1/floors/{floorId}/sectors - slug is auto-generated by backend, send empty string */
  createSector(floorId: string, name: string): Observable<Sector> {
    const request: SectorCreateRequest = { name, slug: '' };
    return this.api.createSector({ floorId, sectorCreateRequest: request });
  }

  /** DELETE /api/v1/sectors/{id} */
  deleteSector(id: string): Observable<void> {
    // El contrato aún no genera este endpoint (CU-05 pendiente de baja); mientras
    // tanto la llamada se monta sobre la misma base URL del runtime config.
    return this.http.delete<void>(`${this.runtime.config().apiBaseUrl}/sectors/${id}`);
  }

  // ===== SPACE ELEMENTS (HU-2.03 / MAP-117)

  /** GET /api/v1/sectors/{sectorId}/elements */
  listSpaceElementsBySector(sectorId: string): Observable<SpaceElement[]> {
    return this.api.listSpaceElementsBySector({ sectorId });
  }

  /** POST /api/v1/sectors/{sectorId}/elements */
  createSpaceElement(
    sectorId: string,
    request: SpaceElementCreateRequest,
  ): Observable<SpaceElement> {
    return this.api.createSpaceElement({ sectorId, spaceElementCreateRequest: request });
  }

  /** PUT /api/v1/sectors/{sectorId}/elements/{elementId} */
  updateSpaceElement(
    sectorId: string,
    elementId: string,
    request: SpaceElementUpdateRequest,
  ): Observable<SpaceElement> {
    return this.api.updateSpaceElement({
      sectorId,
      elementId,
      spaceElementUpdateRequest: request,
    });
  }
}
