import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import type {
  Floor,
  Sector,
  FloorCreateRequest,
  SectorCreateRequest,
  SpaceElement,
  SpaceElementCreateRequest,
  SpaceElementUpdateRequest,
} from '@mapit/api-client';
import { SpacesService } from '@mapit/api-client';
import type { Observable } from 'rxjs';

export interface FloorDraft {
  name: string;
  level: number;
}

export interface SectorDraft {
  name: string;
}

const DEFAULT_ESTABLISHMENT_ID = '00000000-0000-0000-0000-000000000001';
const API_BASE_URL = 'http://localhost:8080/api/v1';

@Injectable({ providedIn: 'root' })
export class SpacesApiService {
  private readonly api = inject(SpacesService);
  private readonly http = inject(HttpClient);

  /** GET /api/v1/establishments/{establishmentId}/floors */
  listFloors(establishmentId: string = DEFAULT_ESTABLISHMENT_ID): Observable<Floor[]> {
    return this.http.get<Floor[]>(`${API_BASE_URL}/establishments/${establishmentId}/floors`);
  }

  /** GET /api/v1/floors/{id} */
  getFloor(id: string): Observable<Floor> {
    return this.api.getFloor({ id });
  }

  /** POST /api/v1/establishments/{establishmentId}/floors */
  createFloor(
    request: FloorCreateRequest,
    establishmentId: string = DEFAULT_ESTABLISHMENT_ID,
  ): Observable<Floor> {
    return this.http.post<Floor>(
      `${API_BASE_URL}/establishments/${establishmentId}/floors`,
      request,
    );
  }

  /** PUT /api/v1/floors/{id} */
  updateFloor(id: string, request: FloorCreateRequest): Observable<Floor> {
    return this.api.updateFloor({ id, floorCreateRequest: request });
  }

  /** DELETE /api/v1/floors/{id} */
  deleteFloor(id: string): Observable<unknown> {
    return this.api.deleteFloor({ id });
  }

  // ===== SECTORS =====

  /** GET /api/v1/floors/{floorId}/sectors */
  listSectorsByFloor(floorId: string): Observable<Sector[]> {
    return this.api.listSectorsByFloor({ floorId });
  }

  /** POST /api/v1/floors/{floorId}/sectors - slug is auto-generated by backend, send empty string */
  createSector(floorId: string, name: string): Observable<Sector> {
    const request: SectorCreateRequest = { name, slug: '' };
    return this.api.createSector({ floorId, sectorCreateRequest: request });
  }

  /** DELETE /api/v1/sectors/{id} */
  deleteSector(id: string): Observable<void> {
    return this.http.delete<void>(`${API_BASE_URL}/sectors/${id}`);
  }

  // ===== SPACE ELEMENTS (HU-2.03 / MAP-117)

  /** GET /api/v1/sectors/{sectorId}/elements */
  listSpaceElementsBySector(sectorId: string): Observable<SpaceElement[]> {
    return this.api.listSpaceElementsBySector({ sectorId });
  }

  /** POST /api/v1/sectors/{sectorId}/elements */
  createSpaceElement(
    sectorId: string,
    request: SpaceElementCreateRequest,
  ): Observable<SpaceElement> {
    return this.api.createSpaceElement({ sectorId, spaceElementCreateRequest: request });
  }

  /** PUT /api/v1/sectors/{sectorId}/elements/{elementId} */
  updateSpaceElement(
    sectorId: string,
    elementId: string,
    request: SpaceElementUpdateRequest,
  ): Observable<SpaceElement> {
    return this.api.updateSpaceElement({
      sectorId,
      elementId,
      spaceElementUpdateRequest: request,
    });
  }
}
